# Generated by Django 4.1.2 on 2022-10-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='User ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fisrt Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('access_hash', models.BigIntegerField(verbose_name='Access Hash')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Group ID')),
                ('link', models.CharField(max_length=255, verbose_name='Link to group')),
                ('access_hash', models.BigIntegerField(verbose_name='Access Hash')),
                ('dt', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
                ('user', models.ManyToManyField(related_name='groups_with_user', to='inviter.user')),
            ],
        ),
    ]
