# Generated by Django 4.1.2 on 2022-10-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation datetime'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation datetime'),
        ),
    ]
