# Generated by Django 4.1.2 on 2022-10-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inviter', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='error_message',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Error message'),
        ),
    ]
